version: "3.7"

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    init: true
    ports:
      - 9090:15672
      - 5672:5672
    networks:
      - rabbitmq

networks:
  rabbitmq:
    external: true
